version: "3"
services: 
    frontend:
        stdin_open: true
        build: ./frontend
        volumes: 
            - ./frontend:/usr/src/app
            - ./usr/src/app/node_modules
        depends_on: 
            - api
        ports:
            - "3000:3000"
    api:
        build: ./server
        volumes: 
            - ./server:/usr/src/app
            - ./usr/src/app/node_modules
        ports:
            - "5000:5000"        